server:
  port: 0

spring:
  application:
    name: item-service
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://127.0.0.1:3307/test
    username: root
    password: 4268
#  datasource:
#    url: jdbc:h2:mem:testdb
#    username: sa
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
      path: /h2-console
  elasticsearch:
    host: localhost:9200
    username: elastic
    password: 12345678
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

eureka:
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

kakao_api_key: kakao-api-key

image:
  path:
    item: C://thing_commerce/images/item